# lucas gatsas Theme/Blog - Jekyll Theme
# the library theme: https://github.com/SpaceG/library
# Author: LucasGatsas
# Theme: library
# Source: https://github.com/spaceg/library
# Mail: space@lucasgatsas.ch
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 雷蛙设计
#What is the name of the events or talks you would like to host? (Example Brownbags, Talks, Lighting Talks)
event_label: Events

description: > # "
  雷蛙设计
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bainj.me" # the base hostname & protocol for your site

#These settings might be able to go?
author: BainJ
twitter_username: ""
github_username:  Reewoow
company_name: Reewoow

# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: true

permalink: /event/:title.html
